use consultas_basicas;
select apellido,oficio,dept_no from emple;
select dept_no,dnombre,loc from depart;
select * from emple;
select * from emple order by apellido;
select * from emple order by dept_no desc;
select * from emple order by dept_no desc, apellido asc;
select * from emple where salario>2000;
select * from emple where oficio="ANALISTA";
select apellido,oficio from emple where dept_no=20;
select * from emple where oficio="VENDEDOR" order by apellido;
select * from emple where dept_no=10 and oficio="ANALISTA" order by apellido;
select * from emple where salario>2000 or dept_no=20;
select * from emple order by oficio,apellido;
select * from emple where salario between 1000 and 2000;
select * from emple where oficio="VENDEDOR" and comision>1000;
select * from emple where oficio="EMPLEADO" and salario>1000 and dept_no=10;
select apellido from emple where comision=0 or comision is null;
select apellido from emple where oficio="VENDEDOR" or oficio="ANALISTA" or oficio="EMPLEADO";
select apellido from emple where oficio not in ('ANALISTA','EMPLEADO') and salario>2000;
select apellido,salario,dept_no from emple where salario>2000 and dept_no in (10,30);
select year(fecha_alt) from emple;
select * from personas;
select dni,apellidos,funcion from personas;
select apellidos from personas where localidad="LORCA";
select apellidos from personas where localidad in ('LORCA','MURCIA');
select * from personas where localidad="MURCIA" and salario>1500;
select * from personas where localidad="MURCIA" and salario>1500 and funcion="DIRECTOR";
select * from personas where funcion="MEDICO" order by apellidos desc;
select distinct localidad from personas;
select * from personas where salario>1500 and funcion="MEDICO" order by salario desc;
select * from personas where salario in ('MEDICO','DIRECTOR');
select * from personas where funcion not in ('CONSERJE') and salario>1500 order by apellidos desc;
select * from personas where localidad in ('MURCIA','CARTAGENA') and cod_hospital=1;
select * from personas where cod_hospital!=2 and localidad="MURCIA";
select funcion from personas order by salario desc limit 1;
select apellidos from personas where funcion="MEDICO" order by salario limit 1;
